### ISSUE TITLE
ValueError: GpuReshape: cannot reshape input of shape (1472, 1000) to shape (1, 1000, 1000).

### ISSUE THREAD

**Issue by singlasahil14** [baidu-research/ba-dls-deepspeech#11]
Just after I start training the model, I get the following error:
![screen shot 2016-12-07 at 3 48 06 pm](https://cloud.githubusercontent.com/assets/6660192/20963746/b6c9a140-bc94-11e6-9553-c36871e347a0.png)

**Comment by aglotero** [comment]
Probably you are experiencing the same issue that I had experienced: https://github.com/baidu-research/ba-dls-deepspeech/issues/9

**Comment by singlasahil14** [comment]
Solved. Most probably a bug in keras.
