### ISSUE TITLE
Is there a model checkpoint available anywhere?

### ISSUE THREAD

**Issue by fjnunes** [baidu-research/ba-dls-deepspeech#15]
Hi, thanks for sharing this code!

Could you (or anyone really) publish a model checkpoint somewhere? This would be helpful for the some of us with low internet connections (65Gb can be a big deal) and not as fast GPUs.

Thanks

**Comment by srvinay** [comment]
There's one - `model.tar.gz` that you can play around with (it's only been trained for 5 iterations).

**Comment by fjnunes** [comment]
Oh excellent! Thanks
