### ISSUE TITLE
RuntimeError when I use python train.py train_corpus.json validation_corpus.json /Users/cheung/baidu-speech/model!

### ISSUE THREAD

**Issue by zhangdapeng1207** [baidu-research/ba-dls-deepspeech#27]
I'm using theano-warp-ctc on OX S 10.12, a RuntimeError raised when I try to train the model. I don't know how to fix it, is there some packages required missing on my computer?

![image](https://user-images.githubusercontent.com/23477770/28509494-53d90748-7075-11e7-9f71-f6664ccf9d71.png)

**Comment by ramaseshan** [comment]
You have to give full path, This message means, the path of the audio is wrong. 
If windows it has to be C:/Users/....
Or on GNU/Linux /home/username/path/to/files

**Comment by zhangdapeng1207** [comment]
Thank you! I have found the solution, just like you said.
