### ISSUE TITLE
Help with testing

### ISSUE THREAD

**Issue by basilabraham123** [baidu-research/ba-dls-deepspeech#5]
While testing the test-clean data set using test.py only 1879 predictions are generated. The test set has 2620 utterances. Is there any parameter to  change so that we get all 2620 predictions. Is there a sample code to use the output_function to generate the posteriors.

**Comment by srvinay** [comment]
You should try changing `https://github.com/baidu-research/ba-dls-deepspeech/blob/master/data_generator.py#L53` to increase the `max_duration` argument. Currently, that's set to 10 seconds so the code ignores utterances longer than that.

**Comment by basilabraham123** [comment]
Thank you sir
